<?php

use Illuminate\Foundation\Testing\DatabaseMigrations;
class InvoicesTest extends TestCase
{
    use DatabaseMigrations;

    private $responseModel;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setAuthToken();
        $this->createBeforeDemand();
        $this->createDemandWithItems(1);
        $this->responseModel = $this->createResponseWithItems(3, [
            'company_id' => $this->company->id
        ]);

    }


    public function testCreateAuth()
    {
        $this->post('/api/invoices')
            ->seeStatusCode(401);
    }

    public function testCreate()
    {
        $data = [
            'responseItems' => [
                $this->responseModel->responseItems[0]->id,
                $this->responseModel->responseItems[1]->id
            ]
        ];

        $r = $this->post('/api/invoices?token=' . $this->token, $data);
            $r->seeStatusCode(201)
            ->seeHeader('location', '/invoices/1');

        $items = $this->responseModel->invoices;
        $this->assertCount(1, $items);
        $item = $items[0];
        $this->assertCount(2, $item->responseItems);
    }

    public function testNotCreateRights()
    {
        $company = factory(\App\Company::class)->create();
        $response = $this->createResponseWithItems(1, [
            'company_id' => $company->id
        ]);
        $data = [
            'responseItems' => [
                $this->responseModel->responseItems[0]->id,
                $response->responseItems[0]->id
            ]
        ];

        $this->post('/api/invoices?token=' . $this->token, $data)
            ->seeStatusCode(403);

        $items = $this->responseModel->invoices;
        $this->assertCount(0, $items);
    }

    public function testFileAuth()
    {
        $this->get('/api/invoices/1/files/abba')
            ->seeStatusCode(401);
    }

    public function testFileForeign()
    {
        //invoice
        $company = factory(\App\Company::class)->create();
        $response = factory(\App\Demand\Response::class)->create([
            'company_id' => $company->id
        ]);
        $item = factory(\App\Demand\Invoice::class)->create([
            'response_id' => $response->id,
        ]);

        $r = $this->get('/api/invoices/' . $item->id . '/files/abba?token=' . $this->token)
            ->seeStatusCode(403);
    }

    private function createFile($invoiceId)
    {
        $oldmask = umask(0);
        //create file
        $faker = Faker\Factory::create();
        $path = storage_path('app/invoices/' . $invoiceId);
        $filepath = $faker->file('/tmp', $path);
        chmod($filepath, 0777);
        umask($oldmask);

        return $filepath;
    }


    public function testFileRight()
    {
        //invoice
        $filename = File::basename($filepath);
        $item = factory(\App\Demand\Invoice::class)->create([
            'response_id' => $this->responseModel->id,
            'filename' => $filename
        ]);

        $this->get('/api/invoices/' . $item->id . '/files/' . $filename . '?token=' . $this->token)
            ->seeStatusCode(200);
        \File::delete($filepath);
    }

    public function testUpdateAuth()
    {
        $this->put('/api/invoices/11')
            ->seeStatusCode(401);
    }

    public function testUpdateRight()
    {
        $item = factory(\App\Demand\Invoice::class)->create([
            'response_id' => $this->responseModel->id
        ]);

        $path = storage_path('app/tests/report.xls');

        $file = new \Illuminate\Http\UploadedFile($path, 'file', 'application/excel', 446, null, true);
        $data = [
            'file' => $file
        ];

        $r = $this->put('/api/invoices/' . $item->id . '/?token=' . $this->token,
            $data
        );
        var_dump($r->response->content());die;
        $r->seeStatusCode(201);

        $invoice = \App\Demand\Invoice::first();
        $this->assertEquals('report.csv', $invoice->filename);
        $this->assertTrue(file_exists($invoice->filepath));

         $service = new \App\Services\InvoiceService();
         $service->deleteItem($invoice);

        File::delete($path);
    }


    public function testDeleteAuth()
    {
        $this->delete('/api/invoices/11')
            ->seeStatusCode(401);
    }

    public function testDeleteRight()
    {
        $item = factory(\App\Demand\Invoice::class)->create([
            'response_id' => $this->responseModel->id
        ]);

        $r = $this->delete('/api/invoices/' . $item->id . '/?token=' . $this->token);
        $r->seeStatusCode(202);

        $this->assertEquals(0, \App\Demand\Invoice::count());
    }

    public function testDeleteForeign()
    {
        $company = factory(\App\Company::class)->create();
        $response = $this->createResponseWithItems(1, [
            'company_id' => $company->id
        ]);
        $item = factory(\App\Demand\Invoice::class)->create([
            'response_id' => $response->id
        ]);

        $r = $this->delete('/api/invoices/' . $item->id . '/?token=' . $this->token);
        $r->seeStatusCode(403);

        $this->assertEquals(1, \App\Demand\Invoice::count());
    }





}
