<?php
/**
 * Created by PhpStorm.
 * User: kirya
 * Date: 13.09.16
 * Time: 16:24
 */

namespace App\Http\Requests\Demand;


use App\Demand\Demand;
use App\Http\Requests\ApiRequest;
use App\Services\DemandService;
use Swagger\Annotations as SWG;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 *
 * @SWG\Definition(
 *      definition="StatusDemandRequest",
 *      @SWG\Property(
 *         property="id",
 *         description="id demand",
 *         type="int",
 *      ),
 *  )
 *
 * Class StatusDemandRequest
 * @package App\Http\Requests
 */
class StatusDemandRequest extends ApiRequest
{
    /**
     * @var Demand
     */
    private $item;

    /**
     * @var DemandService
     */
    private $demandService;

    public function __construct(array $query = array(), array $request = array(), array $attributes = array(), array $cookies = array(), array $files = array(), array $server = array(), $content = null)
    {
        $this->demandService = new DemandService();
        parent::__construct($query, $request, $attributes, $cookies, $files, $server, $content); // TODO: Change the autogenerated stub
    }

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }


    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return ['id' => 'numeric|required'];
    }


    /**
     * @return Demand
     */
    public function getDemand()
    {
        if (!isset($this->item)) {
            $this->item = $this->demandService->findItem((int)$this->get('id'));
            if (!isset($this->item)) {
                throw new NotFoundHttpException('Not found item');
            }
        }
        return $this->item;
    }



}

