<?php
/**
 * Created by PhpStorm.
 * User: kirya
 * Date: 10.07.17
 * Time: 10:07
 */

namespace App\Http\Requests;

use App\Company;
use App\Services\CompanyService;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;


/**
 *
 *
 *
 * Class UpdateCompanyRequest
 * @package App\Http\Requests
 *
 *
 */
class CompanyRequest extends ApiRequest
{

    /**
     * @var Company
     */
    private $item;

    /**
     * @var CompanyService
     */
    private $service;

    public function __construct(array $query = array(), array $request = array(), array $attributes = array(), array $cookies = array(), array $files = array(), array $server = array(), $content = null)
    {
        $this->service = new CompanyService();
        parent::__construct($query, $request, $attributes, $cookies, $files, $server, $content); // TODO: Change the autogenerated stub
    }


    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return $this->user()->can('update', $this->getCompany());
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
        ];
    }

    /**
     * @return Company
     */
    public function getCompany()
    {
        if (!isset($this->item)) {
            $this->item = $this->service->findItem((int)$this->route('id'));
            if (!isset($this->item)) {
                throw new NotFoundHttpException('Not found item');
            }
        }
        return $this->item;
    }

}