<?php
/**
 * Created by PhpStorm.
 * User: kirya
 * Date: 18.09.16
 * Time: 12:50
 */

namespace App\Http\Requests;

use App\Demand\Invoice;
use App\Services\InvoiceService;
use Illuminate\Http\Request;

class UpdateInvoiceRequest extends ApiRequest
{
    /**
     * @var Invoice
     */
    private $item;

    /**
     * @var InvoiceService
     */
    private $invoiceService;

    public function __construct(array $query = array(), array $request = array(), array $attributes = array(), array $cookies = array(), array $files = array(), array $server = array(), $content = null)
    {
        $this->invoiceService = new InvoiceService();
        parent::__construct($query, $request, $attributes, $cookies, $files, $server, $content); // TODO: Change the autogenerated stub
    }


    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return $this->user()->can('update', $this->getInvoice());
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'file' => 'file',
            'file' => 'mimes:csv,xls,doc,docm,pdf,xlsx'
        ];
    }

    /**
     * @return Invoice
     */
    public function getInvoice()
    {
        if (!isset($this->item)) {
            $this->item = $this->invoiceService->findItem((int)$this->route('id'));
        }
        return $this->item;
    }


}