<?php

use Illuminate\Foundation\Testing\DatabaseMigrations;

class CompaniesTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setAuthToken();
    }



    public function testSearch()
    {
        $spheres = factory(\App\Type\Sphere::class, 4)->create();
        $regions = factory(\App\Type\Region::class, 4)->create();
        $companies = factory(\App\Company::class, 10)->create();


        $this->attachCompanyToSphereAndRegion($companies[0],
            [$spheres[0]->id, $spheres[3]->id],
            [$regions[0]->id, $regions[3]->id]
        );
        $this->attachCompanyToSphereAndRegion($companies[1],
            [$spheres[0]->id, $spheres[2]->id],
            [$regions[0]->id]
        );
        $this->attachCompanyToSphereAndRegion($companies[2],
            [$spheres[2]->id],
            [$regions[0]->id, $regions[1]->id, $regions[2]->id]
        );
        $this->attachCompanyToSphereAndRegion($companies[3],
            [$spheres[2]->id, $spheres[3]->id],
            [$regions[3]->id, $regions[1]->id, $regions[2]->id]
        );

        $data = http_build_query([
            'spheres' => [$spheres[3]->id, $spheres[2]->id],
            'regions' => [$regions[0]->id]
        ]);
        $r = $this->get('/api/companies/search?token=' . $this->token . '&' . $data);
            $r->seeStatusCode(200)
            ->seeJsonStructure([
                'count'
            ]);

        $count = json_decode($r->response->content())->count;
        $this->assertEquals(3, $count);


        $data = http_build_query([
            'spheres' => [$spheres[0]->id],
            'regions' => [$regions[0]->id, $regions[1]->id]
        ]);
        $r = $this->get('/api/companies/search?token=' . $this->token . '&' . $data)
            ->seeStatusCode(200)
            ->seeJsonStructure([
                'count'
            ]);

        $count = json_decode($r->response->content())->count;
        $this->assertEquals(2, $count);


    }



    public function testSearchAuth()
    {
        $this->get('/api/companies/search')
            ->seeStatusCode(401);
    }



}
