<?php

use Illuminate\Foundation\Testing\DatabaseMigrations;

class ConfirmationsTest extends TestCase
{
    use DatabaseMigrations;

    /**
     * @var \App\User
     */
    protected $user;

    /**
     * @var \App\User
     */
    private $confirmatingUser;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        factory(\App\Company::class)->create();
        $this->user = factory(\App\User::class)->create();
        $this->confirmatingUser = factory(\App\User::class, 'confirmating')->create();
    }


    public function testCreate()
    {
        $r = $this->post(
            'api/users/confirmations',
            [
                'confirmation_code' => $this->confirmatingUser->confirmation_code
            ]
        )
            ->seeStatusCode(201)
            ->seeHeader('location', '/users/' . $this->confirmatingUser->id);
    }

    public function testErrorAlreadyCreating()
    {
        $this->post(
            'api/users/confirmations',
            [
                'confirmation_code' => $this->user->confirmation_code
            ]
        )
            ->seeStatusCode(422);
    }

    public function testErrorWithoutConfirmationCode()
    {
        $this->post(
            'api/users/confirmations',
            [
            ]
        )
            ->seeStatusCode(422);
    }

    public function testErrorWithNotRightConfirmationCode()
    {
        $this->post(
            'api/users/confirmations',
            [
                'confirmation_code' => str_random(30)
            ]
        )
            ->seeStatusCode(500);
    }

}
