<?php

use Illuminate\Foundation\Testing\DatabaseMigrations;

class QuantitiesTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }



    public function testIndex()
    {
        $regions = factory(\App\Type\Quantity::class, 4)->create();

        $r = $this->get('/api/quantities');
            $r->assertStatus(200)
            ->assertJsonStructure([
                    '*' => [
                        'id',
                        'title'
                    ]
            ]);

        $regions = $r->json();
        $this->assertEquals(4, count($regions));

    }






}
