<?php

use Illuminate\Foundation\Testing\DatabaseMigrations;

class RegionsTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setAuthToken();
    }



    public function testIndex()
    {
        $regions = factory(\App\Type\Region::class, 4)->create();

        $r = $this->get('/api/regions?token=' . $this->token);
            $r->seeStatusCode(200)
            ->seeJsonStructure([
                'data' => [
                    '*' => [
                        'id',
                        'title'
                    ]
                ]
            ]);

        $regions = json_decode($r->response->content())->data;
        $this->assertEquals(6, count($regions));

    }



    public function testIndexAuth()
    {
        $this->get('/api/regions')
            ->seeStatusCode(401);
    }



}
