<?php
/**
 * Created by PhpStorm.
 * User: kirya
 * Date: 29.07.17
 * Time: 14:20
 */

use Illuminate\Foundation\Testing\DatabaseMigrations;
use App\Demand\Response;
class ResponsesAutoNumberTest extends TestCase
{
    use DatabaseMigrations;

    private $regions;

    private $spheres;

    private $quantities;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setAuthToken();
        $this->regions = factory(\App\Type\Region::class, 3)->create()->pluck('id')->toArray();
        $this->spheres = factory(\App\Type\Sphere::class, 3)->create()->pluck('id')->toArray();
        $this->quantities = factory(\App\Type\Quantity::class, 2)->create()->pluck('id')->toArray();
    }

    public function testCreateNumber()
    {

    }


    public function testUpdateNumber()
    {
        //createDemand
        $this->createBeforeDemand();
        $demand = $this->createDemandWithItems(1);

        //createResponse
        $response = $this->createResponseWithItems(0, [
            'company_id' => $this->company->id,
            'status' => \App\Type\ResponseStatus::DRAFT,
            'demand_id' => $demand->id
        ]);

        $data = [
            'number' => 'siliciumn',
            'readed' => \Carbon\Carbon::create()->toDateTimeString(),
            'desc' => 'sfsdfsd'
        ];

        $r = $this->patch(sprintf('/api/responses/%s?token=%s', $response->id, $this->token), $data);
        $r->assertStatus(202);

        $response = Response::find($response->id);
        $this->assertEquals($data['number'], $response->number);
    }


}
