<?php

use Illuminate\Foundation\Testing\DatabaseMigrations;

class SpheresTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }



    public function testIndex()
    {
        $spheres = factory(\App\Type\Sphere::class, 4)->create();
        $r = $this->get('/api/spheres');
            $r->seeStatusCode(200)
            ->seeJsonStructure([
                    '*' => [
                        'id',
                        'title'
                    ]
            ]);

        $spheres = json_decode($r->response->content());
        $this->assertEquals(4, count($spheres));

    }




}
