<?php

use Illuminate\Foundation\Testing\DatabaseMigrations;

class SpheresTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }



    public function testIndex()
    {
        $spheres = factory(\App\Type\Sphere::class, 4)->create();
        $r = $this->json('GET', '/api/spheres');
            $r->assertStatus(200)
            ->assertJsonStructure([
                    '*' => [
                        'id',
                        'title'
                    ]
            ]);

        $spheres = $r->json();
        $this->assertEquals(4, count($spheres));

    }




}
