FORMAT: 1A

# supp

# Users

## Register user [POST /]
Register a new user with a `username` and `password`.

+ Request (application/json)
    + Body

            {
                "username": "foo",
                "password": "bar"
            }