<?php
/**
 * Created by PhpStorm.
 * User: kirya
 * Date: 04.10.16
 * Time: 22:42
 */

use Illuminate\Support\Facades\Event;
use App\Events\DemandItem\SelectedResponseItemEvent;
use App\Events\DemandItem\UnselectedResponseItemEvent;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class GenerateDemandItemsEventsTest extends \TestCase
{
    use DatabaseMigrations;

    private $demandItem;

    private $responseItem;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createBeforeCompany();
        factory(\App\Company::class)->create();
        $this->createBeforeDemand();
        $demand = $this->createDemandWithItems(1);
        $this->demandItem = $demand->demandItems[0];
        $response = $this->createResponseWithItems(1);
        $this->responseItem = $response->responseItems[0];

    }



    public function testSelected()
    {
        Event::fake();

        $this->demandItem->response_item_id = $this->responseItem->id;
        $this->demandItem->save();

        Event::assertFired(SelectedResponseItemEvent::class, function ($e)  {
            return (
                $e->item->id == $this->demandItem->id and
                $e->item->response_item_id = $this->responseItem->id
            );
        });
    }

    public function testUnselected()
    {
        Event::fake();

        $this->demandItem->response_item_id = $this->responseItem->id;
        $this->demandItem->save();

        $this->demandItem->response_item_id = null;
        $this->demandItem->save();


        Event::assertFired(UnselectedResponseItemEvent::class, function ($e)  {
            return (
                $e->item->id == $this->demandItem->id and
                $e->oldResponseItem->id = $this->responseItem->id
            );
        });
    }

}