<?php
/**
 * Created by PhpStorm.
 * User: kirya
 * Date: 04.10.16
 * Time: 22:42
 */

use Illuminate\Support\Facades\Event;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class GenerateDemandEventsTest extends \TestCase
{
    use DatabaseMigrations;

    public $demand;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createBeforeCompany();
        factory(\App\Company::class)->create();
        $this->createBeforeDemand([
            'status' => \App\Type\DemandStatus::ACTIVE
        ]);
        $this->demand = $this->createDemandWithItems(1);
    }



    public function testUpdated()
    {
        Event::fake();
        $this->demand->status = \App\Type\DemandStatus::ACTIVE;
        $this->demand->save();

        Event::fake();

        $this->demand->status = \App\Type\DemandStatus::DELETED;
        $this->demand->save();

        Event::assertFired(\App\Events\Demand\DeleteDemandEvent::class, function ($e)  {
            return (
                $e->item->id == $this->demand->id
            );
        });
    }

    public function testNotUpdated()
    {
        Event::fake();
        $this->demand->status = \App\Type\DemandStatus::DELETED;
        $this->demand->save();

        Event::fake();

        $this->demand->status = \App\Type\DemandStatus::ACTIVE;
        $this->demand->save();

        Event::assertNotFired(\App\Events\Demand\DeleteDemandEvent::class);
    }

}