<?php
/**
 * Created by PhpStorm.
 * User: kirya
 * Date: 18.09.16
 * Time: 20:07
 */

use Illuminate\Foundation\Testing\DatabaseMigrations;
use App\Demand\Response;

class CreateDraftResponsesForDemandJobAutoNumberTest extends TestCase
{
    use DatabaseMigrations;

    private $spheres;

    private $regions;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        //company
        $this->spheres = factory(\App\Type\Sphere::class, 2)->create();
        $this->regions = factory(\App\Type\Region::class, 2)->create();

        $this->createBeforeCompany();
        $this->company = factory(\App\Company::class)->create();
        $this->attachCompanyToSphereAndRegion(
            $this->company,
            [$this->spheres[0]->id],
            [$this->regions[0]->id]
        );
    }

    private function createDemand()
    {
        $companyDemand = factory(\App\Company::class)->create();
        $this->attachCompanyToSphereAndRegion(
            $companyDemand,
            [$this->spheres[0]->id],
            [$this->regions[0]->id]
        );
        $this->createBeforeDemand();
        return $this->createDemandWithItems(1, [
            'company_id' => $companyDemand->id,
            'spheres' => [$this->spheres[0]->id],
            'regions' => [$this->regions[0]->id]
        ]);
    }


    public function testHandleCreateAuto()
    {
        $company = factory(\App\Company::class)->create();
        $this->attachCompanyToSphereAndRegion(
            $company,
            [$this->spheres[0]->id],
            [$this->regions[0]->id]
        );

        $demand = $this->createDemand();

        $job = new \App\Jobs\CreateDraftResponseForDemandJob($demand);
        $job->handle();

        $responses = Response::query()->get();
        $this->assertCount(2, $responses);

        $response = $responses[0];
        $this->assertEquals(1, $response->number);

        $response = $responses[1];
        $this->assertEquals(1, $response->number);

    }

    public function testHandleCreateAutoNext()
    {
        $demand = $this->createDemand();
        $demand2 = $this->createDemand();

        $ownResponse = factory(Response::class)->create([
            'company_id' => $this->company->id,
            'number' => 'sel2',
            'demand_id' => $demand2->id
        ]);


        $foreignCompany = factory(\App\Company::class)->create();
        $foreignResponse = factory(Response::class)->create([
            'company_id' => $foreignCompany->id,
            'number' => '5',
            'demand_id' => $demand2->id
        ]);

        $job = new \App\Jobs\CreateDraftResponseForDemandJob($demand);
        $job->handle();

        $response = Response::query()->whereCompanyId($this->company->id)->orderBy('id','DESC')->first();
        $this->assertEquals(3, $response->number);
    }



}